name = "tai-backend"
main = "worker-smart.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
# GMAIL_USER = "amaravadhibharath@gmail.com" # Optional, defaults to code
